"""add_notification_fields_to_users

Revision ID: 0a01730dc3ba
Revises: 061efd6aa36b
Create Date: 2026-04-02 22:34:18.030481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a01730dc3ba'
down_revision: Union[str, None] = '061efd6aa36b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fcm_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('notify_morning_focus', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('users', sa.Column('notify_evening_reflect', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('users', sa.Column('notify_midweek_progress', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notify_midweek_progress')
    op.drop_column('users', 'notify_evening_reflect')
    op.drop_column('users', 'notify_morning_focus')
    op.drop_column('users', 'fcm_token')
    # ### end Alembic commands ###
