"""rename_time_to_start_end_time_on_tasks

Revision ID: 8db07f4d7e81
Revises: 0b398a665110
Create Date: 2026-04-13 11:11:02.433064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8db07f4d7e81'
down_revision: Union[str, None] = '0b398a665110'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('start_time', sa.Time(), nullable=True))
    op.add_column('tasks', sa.Column('end_time', sa.Time(), nullable=True))
    op.drop_column('tasks', 'time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('time', postgresql.TIME(), autoincrement=False, nullable=True))
    op.drop_column('tasks', 'end_time')
    op.drop_column('tasks', 'start_time')
    # ### end Alembic commands ###
