"""add_description_time_skip_reason_to_tasks

Revision ID: e1de57ae4746
Revises: 0a01730dc3ba
Create Date: 2026-04-11 08:40:24.455834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1de57ae4746'
down_revision: Union[str, None] = '0a01730dc3ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('time', sa.Time(), nullable=True))
    op.add_column('tasks', sa.Column('skip_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'skip_reason')
    op.drop_column('tasks', 'time')
    op.drop_column('tasks', 'description')
    # ### end Alembic commands ###
