"""add_ai_pattern_insight_to_reflections

Revision ID: f76fc44f0e59
Revises: eed4bb085365
Create Date: 2026-02-25 21:20:15.849070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f76fc44f0e59'
down_revision: Union[str, None] = 'eed4bb085365'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weekly_reflections', sa.Column('ai_pattern_insight', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weekly_reflections', 'ai_pattern_insight')
    # ### end Alembic commands ###
